apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: spark
  labels:
    app: test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: test
      namespace: spark
      labels:
        app: test
    spec:
      serviceAccountName: spark
      containers:
      - name: test
        image: datamechanics/spark:3.1-latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["/opt/entrypoint.sh /opt/spark/bin/spark-submit --version && sleep 6000"]
